config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  get "/blockly" => "index#blockly"
  get "/icons" => "index#icons"
  get "/privacy-policy" => "index#privacy_policy"

  constraints subdomain: "sub" do
    get "/sub" => "index#sub"
  end

  constraints subdomain: "whisper" do
    root "whisper#show", as: :whisper_root
  end

  post "tesla/api/1/vehicles/:vin/command/:command" => "vehicles#command"
  post "tesla/oauth2/v3/token" => "vehicles#token"

  root "index#home"
  post "/talk" => "index#talk"
  get "/nest_subscribe" => "index#nest_subscribe"
  post "/jarvis" => "jarvis#command"
  post "proxy" => "proxy#proxy"
  post "/printer_control" => "printers#control"
  get "map" => "index#map"
  get "playground" => "index#playground"
  resource :ping, only: :create

  resource :whisper, only: [:show], controller: :whisper

  namespace :internal do
    get "auth", to: "auth#check"
  end

  namespace :api do
    namespace :v1 do
      post :alexa, controller: :alexa

      resources :lists, only: [:index, :show, :update, :create, :destroy] do
        post :reorder, on: :collection
        put :order_items, on: :member

        resources :list_items, only: [:index, :show, :update, :create, :destroy] do
          patch :update, on: :collection
          delete :destroy, on: :collection
        end

        resources :sections, only: [:index, :show, :update, :create, :destroy] do
          patch :update, on: :collection
          delete :destroy, on: :collection
        end
        # resources :user_lists, only: [:index, :create, :destroy], path: :users
      end
    end
  end

  resource :jarvis, only: [:show, :update], controller: :quick_actions, as: :user_dashboard do
    get :sync_badge
    get :render_widget
  end

  scope path: :jarvis do
    resources :meal_builders
    resources :list_builders do
      get :manifest, on: :member
      post :toggle_item, on: :member
      patch :update_stock, on: :member
    end
  end

  resources :dashboards, only: [:show, :update], controller: :quick_actions do
    get "/create", on: :collection, action: :get_create
    get :sync_badge
    get :render_widget
  end
  resources :prompts, only: [:index, :show, :update, :destroy], path: :prompts

  scope module: :users do
    get :login,         controller: :sessions,      action: :new
    post :login,        controller: :sessions,      action: :create
    get :logout,        controller: :sessions,      action: :destroy
    delete :logout,     controller: :sessions,      action: :destroy
    get :register,      controller: :registrations, action: :new
    post :register,     controller: :registrations, action: :create
    patch :register,    controller: :registrations, action: :create
    post :guest_signup, controller: :registrations, action: :guest_signup
  end

  resource :money_buckets, path: "/bucket"

  post "webhooks/tesla_telemetry" => "webhooks#tesla_telemetry"
  post "webhooks/tesla_local" => "webhooks#tesla_local"
  post "jil/trigger/:trigger" => "webhooks#jil"
  post "jil/trigger" => "webhooks#jil"
  post "webhooks/jil(/:uuid)" => "webhooks#execute_task"
  get "webhooks/jil(/:uuid)" => "webhooks#execute_task"
  post "webhooks/battery" => "webhooks#battery"
  post "webhooks/report" => "webhooks#report"
  get "webhooks/local_ping" => "webhooks#local_ping"
  post "webhooks/local_ping" => "webhooks#local_ping"
  post "webhooks/jenkins" => "webhooks#jenkins"
  post "webhooks/post" => "webhooks#post"
  post "webhooks/google_pub_sub" => "webhooks#google_pub_sub"
  post "webhooks/email" => "webhooks#email"
  post "webhooks/speak" => "webhooks#speak"
  post "webhooks/notify" => "webhooks#notify"
  get "webhooks/uptime" => "webhooks#uptime"
  post "webhooks/uptime" => "webhooks#uptime"
  post "webhooks/command" => "webhooks#command"
  get "webhooks/auth" => "webhooks#auth"
  get "webhooks/auth/:service" => "webhooks#auth"
  get "webhooks/oauth/:service" => "webhooks#auth"
  post "push_notification_subscribe" => "webhooks#push_notification_subscribe"
  post "push_notification_unsubscribe" => "webhooks#push_notification_unsubscribe"
  post "push_diagnostic" => "webhooks#push_diagnostic"

  get "dashboard" => "dashboard#show"
  resource :dashboard, controller: :dashboard, only: [:show] do
    get :demo, on: :collection
    collection do
      get :octoprint_session
    end
  end

  resource :nfc, only: [:show]

  resources :emails, except: [:destroy, :edit]
  resources :log_trackers, only: [:index, :show]
  post "/ips/ban" => "log_trackers#ban", as: :ban_ip

  resources :surveys
  resources :survey_responses

  resource :calc, only: [:show]

  resources :action_events do
    get :calendar, on: :collection
    get :pullups, on: :collection
    get :feelings, on: :collection
  end

  resource :inventory, controller: :inventory_management do
    resources :boxes do
      collection do
        get :batch
      end
    end
    get :export
    post :import
    post :restore
  end
  get "/b/:id" => "inventory_management#box", as: :box

  resources :scheduled_tasks, path: :schedules

  resource :summoners_war do
    get :runes
    resources :monsters
    resources :monster_skills
  end

  get :account, controller: :users
  resources :api_keys, except: :show
  resources :users, only: [:new, :create, :update]
  resources :lists do
    post :reorder, on: :collection
    member do
      get :manifest
      post :modify_from_message
      post :receive_update
    end
    resources :user_lists, only: [:index, :create, :destroy], path: :users
    resources :list_items
    resources :sections, only: [:edit, :create, :update, :destroy]
  end

  resources :cards, only: [] do
    collection do
      get :deck
    end
  end

  get :random, controller: :random, action: :index
  resources :gcode_splitter, only: [:index]
  resources :colors, only: [:index]
  resources :anonicons, only: [:index, :show], constraints: { id: /[0-9.a-zA-Z]+/ }
  resources :qr_labels, only: [:index, :show]
  get :"svg-editor", controller: :svg_editors, action: :show

  resource :rlcraft, only: [:show, :update]

  resource :little_world, only: [:show] do
    post :save_location
    get :player_login
    get :character_builder
    post :change_clothes
    get :change_clothes, action: :load_character
  end

  namespace :jil do
    get :/, action: :index, controller: :tasks
    get "t/:id" => "tasks#trigger"
    resources :executions, only: [:index, :show] do
      post :replay, on: :member
    end
    post "tasks/reorder", to: "tasks#reorder", as: :reorder_tasks
    resources :tasks do
      post :run, on: :member
      post :duplicate, on: :member
      post :shared_users, on: :member
      post :archive, on: :member
      post :unarchive, on: :member
      resources :executions, only: [:index, :show] do
        post :replay, on: :member
      end
    end
    resources :task_folders, only: [:create, :update, :destroy] do
      post :toggle_collapsed, on: :member
    end
    resources :user_cache, path: :cache
  end
  get "t/:id" => "jil/tasks#trigger"
  # Must be after `jil` namespace so it doesn't overwrite existing routes
  post "jil/:uuid" => "webhooks#execute_task"
  get "jil/:uuid" => "webhooks#execute_task"

  resources :climbs do
    patch :mark, on: :collection
  end

  namespace :bowling, as: nil do
    resources :bowlers, only: [:create] do
      get :throw_stats, on: :collection
    end
    resources :bowling_leagues, path: :leagues do
      get :tms, on: :member
    end
    resources :bowling_sets, path: :series do
      delete "bowler/:bowler_id", on: :member, action: :remove_bowler
    end
    resources :bowling_games, path: "/"
  end

  resources :contacts, except: :show do
    resources :addresses, except: :show
  end
  resources :folders
  resources :pages, except: :index
  get "/pages", to: "folders#index"
  resources :recipes, param: :friendly_id do
    post :export_to_list, on: :member
  end

  resource :maze, only: [:show] do
    collection do
      post ":seed/solve", action: :solve
      match ":seed/solve", action: :preflight, via: :options
      post "/", action: :redirect
      get ".txt", action: "show"
      get ":seed", action: "show"
      get ":seed.txt", action: "show"
    end
  end

  require "sidekiq/web"
  # constraints ->(req) { binding.pry } do
  constraints RoleConstraint.new(:admin) do
    mount ::Sidekiq::Web => "/sidekiq"
    mount ::PgHero::Engine, at: "pghero"
  end
  mount ::ActionCable.server => "/cable"
end

app/models/action_event.rb
# == Schema Information
#
# Table name: action_events
#
#  id            :integer          not null, primary key
#  data          :jsonb
#  name          :text
#  notes         :text
#  streak_length :integer
#  timestamp     :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#

class ActionEvent < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  before_save { self.timestamp ||= ::Time.current }

  search_terms :id, :name, :notes, :timestamp

  # Contains ANY
  scope :search_data_actions_any, ->(*qs) {
    where("data -> 'actions' ?| array[:actions]", actions: Array.wrap(qs).flatten.compact)
  }
  # Contains ALL
  scope :search_data_actions_all, ->(*qs) {
    where("data @> ?", { actions: Array.wrap(qs).flatten.compact }.to_json)
  }
end

app/controllers/action_events_controller.rb
class ActionEventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authorize_user_or_guest

  def index
    @events = current_user.action_events
    @events = @events.query(params[:q]) if params[:q].present?
    @events = @events.where(user: current_user)
    @events = @events.order(timestamp: :desc).page(params[:page]).per(50)

    serialize @events
  end

  def calendar
    Time.use_zone(current_user.timezone) {
      @today = Time.current.to_date
      @date = safeparse_time(params[:date]).to_date.end_of_week(:sunday)
      @week = @date.then { |t| (t - 6.days)..t }
      @events = current_user.action_events
      @events = @events.query(params[:q]) if params[:q].present?
      @events = @events.where(user: current_user)
      @events = @events.order(timestamp: :asc)
      @events = @events.where(timestamp: @week.min.beginning_of_day..@week.max.end_of_day)

      grouped_events = @events.group_by { |evt| [evt.timestamp.to_date, evt.timestamp.hour] }
      @cal_events = [[nil, *@week]]
      (0..23).each do |hour|
        @cal_events << [hour, *@week.map { |day| grouped_events[[day, hour]] }]
      end
    }
  end

  def feelings
    Time.use_zone(current_user.timezone) {
      @today = Time.current.to_date

      if params[:start_date].present? && params[:end_date].present?
        @date = start_date = safeparse_time(params[:start_date]).to_date
        end_date = safeparse_time(params[:end_date]).to_date
        @range = (start_date.beginning_of_month..end_date.end_of_month)
      else
        @date = safeparse_time(params[:date]).to_date
        @range = @date.then(&:all_month)
      end

      @events = current_user.action_events.where(name: "Feeling").order(timestamp: :asc)
      @events = @events.where(timestamp: @range)
      @chart_data = @events.map { |evt|
        { id: evt.id, timestamp: evt.timestamp.to_i, data: evt.data }
      }
    }
  end

  def pullups
    Time.use_zone(current_user.timezone) {
      @today = Time.current.to_date
      goal = 1000

      if params[:start_date].present? && params[:end_date].present?
        @date = start_date = safeparse_time(params[:start_date]).to_date
        end_date = safeparse_time(params[:end_date]).to_date
        @range = (start_date.beginning_of_month..end_date.end_of_month)
      else
        @date = safeparse_time(params[:date]).to_date
        @range = @date.then(&:all_month)
      end

      @events = current_user.action_events
      @events = @events.query(params[:q]) if params[:q].present?
      @events = @events.where(user: current_user)
      @events = @events.where(timestamp: @range.min.beginning_of_day..@range.max.end_of_day)
      @events = @events.where(name: "Pullups").order(timestamp: :asc)

      grouped_events = @events.group_by { |evt| evt.timestamp.to_date }
      @range_data = @range.index_with { |date| grouped_events[date] }

      months = {}.tap { |month_hash|
        current_date = @range.first
        while current_date <= @range.last
          month_hash[current_date.strftime("%Y-%m")] = {
            goal: goal,
            days: 1 + Time.days_in_month(current_date.month, current_date.year),
          }
          current_date = current_date.next_month
        end
      }
      @chart_data = {
        labels:   @range_data.map { |date, _evts| date.strftime("%a %-m/%-d/%y") },
        datasets: [
          {
            data:            @range_data.map.with_index { |(date, evts), _idx|
              next if date > @today

              month_data = months[date.strftime("%Y-%m")]
              days_in_month = (month_data[:days] -= 1)
              remaining_goal = month_data[:goal]
              month_data[:goal] -= (evts&.sum { |evt| evt.notes.to_i } || 0)

              next remaining_goal if days_in_month.zero?

              (remaining_goal / days_in_month).clamp(0, goal)
            },
            type:            :line,
            borderColor:     "rgba(255, 160, 1, 0.5)",
            backgroundColor: "rgba(255, 160, 1, 0.5)",
          },
          {
            data:            @range_data.map { |_date, evts|
              evts&.sum { |evt|
                evt.notes.to_i
              } || 0
            },
            backgroundColor: "#0160FF",
          },
        ],
      }

      if @date == @today
        days_left = @date.end_of_month - @today
      else
        days_left = 0
      end

      current = @events.where("notes ~ '\\d+'").sum("notes::integer")
      total_goal = months.length * goal
      total_remaining = total_goal - current
      @stats = {
        remaining:  total_remaining,
        current:    current,
        goal:       total_goal,
        daily_need: days_left.positive? ? total_remaining / days_left.to_f : 0,
      }
    }
  end

  def create
    event = ActionEvent.create(event_params)
    ::Jil.trigger(current_user, :event, event.with_jil_attrs(action: :added))
    ::ActionEventBroadcastWorker.perform_async(event.id)

    respond_to do |format|
      format.json {
        if event.persisted?
          head :ok
        else
          SlackNotifier.notify(event.errors.full_messages.join("\n"))
          head :unprocessable_entity
        end
      }

      format.html {
        flash[:alert] = "Failed to create event: #{event.errors.full_messages.join(" | ")}" unless event.valid?
        redirect_to action_events_path
      }
    end
  end

  def update
    @event = ActionEvent.find(params[:id])

    @event.update(event_params)
    ::Jil.trigger(current_user, :event, @event.with_jil_attrs(action: :changed))
    ::ActionEventBroadcastWorker.perform_async(@event.id, false)
  end

  def destroy
    event = current_user.action_events.find(params[:id])

    if event.destroy
      ::Jil.trigger(current_user, :event, event.with_jil_attrs(action: :removed))
    else
      flash[:alert] = "Failed to destroy event."
    end

    # Reset following event streak info
    matching_events = ActionEvent
      .where(user_id: event.user_id)
      .ilike(name: event.name)
      .where.not(id: event.id)
    following = matching_events.where("timestamp > ?", event.timestamp).order(:timestamp).first
    UpdateActionStreak.perform_async(following.id) if following.present?
    # / streak info

    ActionEventBroadcastWorker.perform_async
    ::RecentEventsBroadcast.call if event.present?
    redirect_to request.referer || action_events_path
  end

  private

  def event_params
    if params.key?(:action_event)
      prepared_params = form_event_params
    else
      prepared_params = raw_event_params
    end

    prepared_params.merge!(user: current_user)

    prepared_params.tap { |whitelist|
      if whitelist[:notes].to_s.match?(/^(-|\+)\d+/)
        offset_time = whitelist[:notes][/^(-|\+)\d+/].to_i
        whitelist[:notes] = whitelist[:notes].sub(/^(-|\+)\d+ ?/, "")
        time = safeparse_time(whitelist[:timestamp])
        whitelist[:timestamp] = time + offset_time.minutes
      end
    }
  end

  def raw_event_params
    params.to_unsafe_h.slice(:name, :timestamp, :notes, :data).tap { |whitelist|
      (params[:event_name].presence || params.dig(
        :action_event,
        :event_name,
      )).presence&.tap { |name|
        whitelist[:name] ||= name
      }
      whitelist.delete(:data).presence&.tap { |data|
        raw_json = Tokenizer.tokenize(data.to_s, only: { "\"" => "\"" }) { |str|
          str.gsub(/\n?\s*(\w+):/) { |found|
            key = Regexp.last_match[1]
            key.match?(/__TOKEN\d+__/) ? found : " \"#{key}\":"
          }
        }
        json = BetterJsonSerializer.load(raw_json)
        whitelist[:data] = json if json.is_a?(::Hash) || json.is_a?(::Array)
      }
    }
  end

  def form_event_params
    params.require(:action_event).permit(
      :name,
      :notes,
      :timestamp,
      :data,
    ).tap { |whitelist|
      (params[:event_name].presence || params.dig(
        :action_event,
        :event_name,
      )).presence&.tap { |name|
        whitelist[:name] ||= name
      }
      whitelist[:timestamp] = whitelist[:timestamp].presence || Time.current
    }
  end

  def safeparse_time(time, fallback=::Time.current)
    return fallback if time.blank?

    if time.is_a?(String)
      begin
        return Time.zone.parse(time)
      rescue StandardError
        return fallback
      end
    else
      time
    end
  end
end

app/views/action_events/calendar.html.erb
<%= form_tag nil, method: :get, enforce_utf8: false, authenticity_token: false do |f| %>
  <input type="text" name="q" value="<%= params[:q] %>" placeholder="Filter">
<% end %>

<div class="text-center" style="margin-bottom: 10px;">
  <%= link_to "List", action_events_path(request.query_parameters) %>
  <%= link_to "Feelings", feelings_action_events_path %>
</div>

<div class="text-center" style="margin: 20px 0;">
  <%= link_to "< Prev week", request.query_parameters.merge(date: @date - 1.week) %>
  - <%= link_to "Today", request.query_parameters.except(:date) %> -
  <%= link_to "Next week >", request.query_parameters.merge(date: @date + 1.week) %>
</div>

<div class="calendar">
  <% @cal_events.each_with_index do |row, ridx| %>
    <% evts = row[1..].flatten %>
    <% row.each_with_index do |col, cidx| %>
      <% if ridx == 0 %>
        <div class="cal-date <%= :today if @today == col %>"><%= col&.strftime("%a %-m/%-d/%y") %></div>
      <% elsif cidx == 0 %>
        <div class="cal-hour <%= :mini if evts.none? %>">
          <%=
            case col
            when 0 then :Midnight
            when 12 then :Noon
            when ..12 then "#{col}am"
            when 12.. then "#{col-12}pm"
            end
          %>
        </div>
      <% else %>
        <div class="cal-cell">
          <% col&.each do |evt| %>
            <span title="<%= evt.notes %>"><%= evt.name %></span><br>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/action_events/feelings.html.erb
<% content_for(:head) do %>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns"></script>
<% end %>

<div class="text-center" style="margin-bottom: 10px;">
  <%= link_to "List", action_events_path(request.query_parameters) %>
  <%= link_to "Calendar", calendar_action_events_path(request.query_parameters) %>
</div>

<div class="text-center" style="margin: 20px 0;">
  <%= link_to "< Prev month", request.query_parameters.except(:start_date, :end_date).merge(date: @date - 1.month) %>
  - <%= link_to "Today", request.query_parameters.except(:start_date, :end_date, :date) %> -
  <%= link_to "Next month >", request.query_parameters.except(:start_date, :end_date).merge(date: @date + 1.month) %>
  <br>
  <%= link_to "All Year", request.query_parameters.except(:date).merge(start_date: @date.beginning_of_year, end_date: @date.end_of_year) %>
</div>

<div class="feelings-charts no-markdown" data-feelings-data="<%= @chart_data.to_json %>"></div>

app/views/action_events/index.html.erb
<%= meta_title "Events", include_name: false %>

<%= form_tag nil, method: :get, enforce_utf8: false, authenticity_token: false do |f| %>
  <input type="text" name="q" value="<%= params[:q] %>" placeholder="Filter">
<% end %>

<%= form_for ActionEvent.new do |f| %>
  <%= f.text_field :name, placeholder: :name, value: f.object.name.presence || params[:name] %>
  <%= f.text_field :notes, placeholder: :notes, value: f.object.notes.presence || params[:notes] %>
  <% Time.use_zone(User.timezone) do %>
    <% f.object.timestamp ||= safeparse_time(params[:timestamp], Time.current) %>
    <%= f.datetime_local_field :timestamp, value: f.object.timestamp.strftime("%Y-%m-%dT%H:%M") %>
  <% end %>
  <%= f.submit %>
<% end %>

<div class="text-center" style="margin-bottom: 10px;">
  <%= link_to "Calendar", calendar_action_events_path(request.query_parameters) %>
  <%= link_to "Feelings", feelings_action_events_path %>
</div>

<div class="text-center">
  <%= page_entries_info @events %>
  <%= paginate @events %>
</div>

<div class="gtable striped bordered wide">
  <div class="thead text-center">
    <div class="th"></div>
    <div class="th">Name</div>
    <div class="th">Notes</div>
    <div class="th">Timestamp</div>
    <div class="th">Streak</div>
  </div>

  <% @events.each do |event| %>
    <div class="trow live-edit-events">
      <%= link_to "X", action_event_path(event), method: :delete, class: "tcell text-center" %>
      <div class="tcell">
        <input data-update-url="<%= action_event_path(event) %>" name="name" value="<%= event.name %>" class="invisi-field" style="width: 100%;" type="text">
      </div>
      <div class="tcell">
        <input data-update-url="<%= action_event_path(event) %>" name="notes" value="<%= event.notes %>" class="invisi-field" style="width: 100%;" type="text">
      </div>
      <div class="tcell">
        <input data-update-url="<%= action_event_path(event) %>" name="timestamp" value="<%= event.timestamp.in_time_zone("Mountain Time (US & Canada)").iso8601[0..-7] %>" class="invisi-field" style="width: 100%;" type="datetime-local">
      </div>
      <div class="tcell">
        <%= event.streak_length || "nil" %>
      </div>
      <div class="sub-row">
        <% json = event.data.present? ? h(JSON.pretty_generate(event.data).gsub(/"(\w+)": /, '\1: ')) : "" %>
        <div class="json-wrapper" style="min-height: <%= 1+(json.count("\n")+1) %>rem">
          <textarea data-update-url="<%= action_event_path(event) %>" name="data" class="invisi-field"><%= json %></textarea>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="text-center">
  <%= paginate @events %>
</div>

app/views/action_events/pullups.html.erb
<% content_for(:head) do %>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.min.js"></script>
<% end %>

<%= form_tag nil, method: :get, enforce_utf8: false, authenticity_token: false do |f| %>
  <input type="text" name="q" value="<%= params[:q] %>" placeholder="Filter">
<% end %>

<div class="text-center" style="margin-bottom: 10px;">
  <%= link_to "List", action_events_path(request.query_parameters) %>
  <%= link_to "Calendar", calendar_action_events_path(request.query_parameters) %>
  <%= link_to "Feelings", feelings_action_events_path %>
</div>

<div class="text-center" style="margin: 20px 0;">
  <%= link_to "< Prev month", params.permit!.except(:action, :controller, :start_date, :end_date).merge(date: @date - 1.month) %>
  - <%= link_to "Today", params.permit!.except(:action, :controller, :start_date, :end_date, :date) %> -
  <%= link_to "Next month >", params.permit!.except(:action, :controller, :start_date, :end_date).merge(date: @date + 1.month) %>
  <br>
  <%= link_to "All Year", params.permit!.except(:action, :controller, :date).merge(start_date: @date.beginning_of_year, end_date: @date.end_of_year) %>
</div>

<div class="text-center">
  <%= @stats[:current] %><small>/<%= @stats[:goal] %></small> | <%= @stats[:remaining] %>r | <%= @stats[:daily_need].round(1) %>d
</div>
<div class="pullups-charts no-markdown" data-pullups-data="<%= @chart_data.to_json %>"></div>