config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  get "/blockly" => "index#blockly"
  get "/icons" => "index#icons"
  get "/privacy-policy" => "index#privacy_policy"

  constraints subdomain: "sub" do
    get "/sub" => "index#sub"
  end

  constraints subdomain: "whisper" do
    root "whisper#show", as: :whisper_root
  end

  post "tesla/api/1/vehicles/:vin/command/:command" => "vehicles#command"
  post "tesla/oauth2/v3/token" => "vehicles#token"

  root "index#home"
  post "/talk" => "index#talk"
  get "/nest_subscribe" => "index#nest_subscribe"
  post "/jarvis" => "jarvis#command"
  post "proxy" => "proxy#proxy"
  post "/printer_control" => "printers#control"
  get "map" => "index#map"
  get "playground" => "index#playground"
  resource :ping, only: :create

  resource :whisper, only: [:show], controller: :whisper

  namespace :internal do
    get "auth", to: "auth#check"
  end

  namespace :api do
    namespace :v1 do
      post :alexa, controller: :alexa

      resources :lists, only: [:index, :show, :update, :create, :destroy] do
        post :reorder, on: :collection
        put :order_items, on: :member

        resources :list_items, only: [:index, :show, :update, :create, :destroy] do
          patch :update, on: :collection
          delete :destroy, on: :collection
        end

        resources :sections, only: [:index, :show, :update, :create, :destroy] do
          patch :update, on: :collection
          delete :destroy, on: :collection
        end
        # resources :user_lists, only: [:index, :create, :destroy], path: :users
      end
    end
  end

  resource :jarvis, only: [:show, :update], controller: :quick_actions, as: :user_dashboard do
    get :sync_badge
    get :render_widget
  end

  scope path: :jarvis do
    resources :meal_builders
    resources :list_builders do
      get :manifest, on: :member
      post :toggle_item, on: :member
      patch :update_stock, on: :member
    end
  end

  resources :dashboards, only: [:show, :update], controller: :quick_actions do
    get "/create", on: :collection, action: :get_create
    get :sync_badge
    get :render_widget
  end
  resources :prompts, only: [:index, :show, :update, :destroy], path: :prompts

  scope module: :users do
    get :login,         controller: :sessions,      action: :new
    post :login,        controller: :sessions,      action: :create
    get :logout,        controller: :sessions,      action: :destroy
    delete :logout,     controller: :sessions,      action: :destroy
    get :register,      controller: :registrations, action: :new
    post :register,     controller: :registrations, action: :create
    patch :register,    controller: :registrations, action: :create
    post :guest_signup, controller: :registrations, action: :guest_signup
  end

  resource :money_buckets, path: "/bucket"

  post "webhooks/tesla_telemetry" => "webhooks#tesla_telemetry"
  post "webhooks/tesla_local" => "webhooks#tesla_local"
  post "jil/trigger/:trigger" => "webhooks#jil"
  post "jil/trigger" => "webhooks#jil"
  post "webhooks/jil(/:uuid)" => "webhooks#execute_task"
  get "webhooks/jil(/:uuid)" => "webhooks#execute_task"
  post "webhooks/battery" => "webhooks#battery"
  post "webhooks/report" => "webhooks#report"
  get "webhooks/local_ping" => "webhooks#local_ping"
  post "webhooks/local_ping" => "webhooks#local_ping"
  post "webhooks/jenkins" => "webhooks#jenkins"
  post "webhooks/post" => "webhooks#post"
  post "webhooks/google_pub_sub" => "webhooks#google_pub_sub"
  post "webhooks/email" => "webhooks#email"
  post "webhooks/speak" => "webhooks#speak"
  post "webhooks/notify" => "webhooks#notify"
  get "webhooks/uptime" => "webhooks#uptime"
  post "webhooks/uptime" => "webhooks#uptime"
  post "webhooks/command" => "webhooks#command"
  get "webhooks/auth" => "webhooks#auth"
  get "webhooks/auth/:service" => "webhooks#auth"
  get "webhooks/oauth/:service" => "webhooks#auth"
  post "push_notification_subscribe" => "webhooks#push_notification_subscribe"
  post "push_notification_unsubscribe" => "webhooks#push_notification_unsubscribe"
  post "push_diagnostic" => "webhooks#push_diagnostic"

  get "dashboard" => "dashboard#show"
  resource :dashboard, controller: :dashboard, only: [:show] do
    get :demo, on: :collection
    collection do
      get :octoprint_session
    end
  end

  resource :nfc, only: [:show]

  resources :emails, except: [:destroy, :edit]
  resources :log_trackers, only: [:index, :show]
  post "/ips/ban" => "log_trackers#ban", as: :ban_ip

  resources :surveys
  resources :survey_responses

  resource :calc, only: [:show]

  resources :action_events do
    get :calendar, on: :collection
    get :pullups, on: :collection
    get :feelings, on: :collection
  end

  resource :inventory, controller: :inventory_management do
    resources :boxes do
      collection do
        get :batch
      end
    end
    get :export
    post :import
    post :restore
  end
  get "/b/:id" => "inventory_management#box", as: :box

  resources :scheduled_tasks, path: :schedules

  resource :summoners_war do
    get :runes
    resources :monsters
    resources :monster_skills
  end

  get :account, controller: :users
  resources :api_keys, except: :show
  resources :users, only: [:new, :create, :update]
  resources :lists do
    post :reorder, on: :collection
    member do
      get :manifest
      post :modify_from_message
      post :receive_update
    end
    resources :user_lists, only: [:index, :create, :destroy], path: :users
    resources :list_items
    resources :sections, only: [:edit, :create, :update, :destroy]
  end

  resources :cards, only: [] do
    collection do
      get :deck
    end
  end

  get :random, controller: :random, action: :index
  resources :gcode_splitter, only: [:index]
  resources :colors, only: [:index]
  resources :anonicons, only: [:index, :show], constraints: { id: /[0-9.a-zA-Z]+/ }
  resources :qr_labels, only: [:index, :show]
  get :"svg-editor", controller: :svg_editors, action: :show

  resource :rlcraft, only: [:show, :update]

  resource :little_world, only: [:show] do
    post :save_location
    get :player_login
    get :character_builder
    post :change_clothes
    get :change_clothes, action: :load_character
  end

  namespace :jil do
    get :/, action: :index, controller: :tasks
    get "t/:id" => "tasks#trigger"
    resources :executions, only: [:index, :show] do
      post :replay, on: :member
    end
    post "tasks/reorder", to: "tasks#reorder", as: :reorder_tasks
    resources :tasks do
      post :run, on: :member
      post :duplicate, on: :member
      post :shared_users, on: :member
      post :archive, on: :member
      post :unarchive, on: :member
      resources :executions, only: [:index, :show] do
        post :replay, on: :member
      end
    end
    resources :task_folders, only: [:create, :update, :destroy] do
      post :toggle_collapsed, on: :member
    end
    resources :user_cache, path: :cache
  end
  get "t/:id" => "jil/tasks#trigger"
  # Must be after `jil` namespace so it doesn't overwrite existing routes
  post "jil/:uuid" => "webhooks#execute_task"
  get "jil/:uuid" => "webhooks#execute_task"

  resources :climbs do
    patch :mark, on: :collection
  end

  namespace :bowling, as: nil do
    resources :bowlers, only: [:create] do
      get :throw_stats, on: :collection
    end
    resources :bowling_leagues, path: :leagues do
      get :tms, on: :member
    end
    resources :bowling_sets, path: :series do
      delete "bowler/:bowler_id", on: :member, action: :remove_bowler
    end
    resources :bowling_games, path: "/"
  end

  resources :contacts, except: :show do
    resources :addresses, except: :show
  end
  resources :folders
  resources :pages, except: :index
  get "/pages", to: "folders#index"
  resources :recipes, param: :friendly_id do
    post :export_to_list, on: :member
  end

  resource :maze, only: [:show] do
    collection do
      post ":seed/solve", action: :solve
      match ":seed/solve", action: :preflight, via: :options
      post "/", action: :redirect
      get ".txt", action: "show"
      get ":seed", action: "show"
      get ":seed.txt", action: "show"
    end
  end

  require "sidekiq/web"
  # constraints ->(req) { binding.pry } do
  constraints RoleConstraint.new(:admin) do
    mount ::Sidekiq::Web => "/sidekiq"
    mount ::PgHero::Engine, at: "pghero"
  end
  mount ::ActionCable.server => "/cable"
end

app/controllers/summoners_wars_controller.rb
class SummonersWarsController < ApplicationController
  def show
    # Should probably be searchable
    @monsters = Monster.where.not(name: nil).order(:name)
  end

  def runes
    mapping_url = "https://raw.githubusercontent.com/Xzandro/sw-exporter/master/app/mapping.js"
    mapping_json = HTTParty.get(mapping_url)
    @mapping = mapping_json.gsub("module.exports = ", "")

    player_file = "/Users/rocconicholls/Library/Group Containers/3L68KQB4HG.group.com.readdle.smartemail/databases/messagesData/1/8527/カタクリの-19659337.json"
    json = JSON.parse(File.read(player_file)).deep_symbolize_keys
    @player_data = json
  end
end

app/views/summoners_wars/runes.html.erb
<div class="skinny-container">
  <div class="ttable striped bordered">
    <div class="tbody monster-table">
      <div class="trow">
        <div class="tcell">Name</div>
        <div class="tcell">Class</div>
        <div class="tcell">Con</div>
        <div class="tcell">Atk</div>
        <div class="tcell">Def</div>
        <div class="tcell">Spd</div>
        <div class="tcell">Resist</div>
        <div class="tcell">Accuracy</div>
        <div class="tcell">Critical Rate</div>
        <div class="tcell">Critical Damage</div>
      </div>
    </div>
  </div>
</div>

<br>

<div class="skinny-container">
  <div class="ttable striped bordered">
    <div class="tbody rune-table">
      <div class="trow">
        <div class="tcell">Rune</div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  function Monster(props) {
    var monster = this
    Object.keys(props).forEach(function(k) {
      monster[k] = props [k]
    })
  }

  Monster.fromData = function(data) {
    var props = {
      data: data,
      class: data.class,
      con: data.con,
      atk: data.atk,
      def: data.def,
      spd: data.spd,
      resist: data.resist,
      accuracy: data.accuracy,
      critical_rate: data.critical_rate,
      critical_damage: data.critical_damage
    }
    props.name = mapping_data.getMonsterName(data.unit_master_id)
    // set human-readable names from mappings
    return new Monster(props)
  }

  function Rune(props) {
    var rune = this
    Object.keys(props).forEach(function(k) {
      rune[k] = props[k]
    })
  }

  Rune.fromData = function(data) {
    var props = {
      data: data
    }
    // set human-readable names from mappings
    return new Rune(props)
  }

  player_data = <%= @player_data.to_json.html_safe %>
  mapping_data = <%= @mapping.html_safe %>

  monsters = []
  runes = []

  player_data.runes.forEach(function(rune_data) {
    runes.push(Rune.fromData(rune_data))
  })

  player_data.unit_list.forEach(function(monster_data) {
    var monster = Monster.fromData(monster_data)
    monster.parsed_runes = []

    monster_data.runes.forEach(function(rune_data) {
      var rune = Rune.fromData(rune_data)
      runes.push(rune)
      monster.parsed_runes.push(rune)
    })

    monsters.push(monster)
  })

  // ================================ Add the monsters to a table

  var table = document.querySelector(".monster-table")
  monsters.forEach(function(monster) {
    var row = document.createElement("div")
    try {
      row.classList.add("trow")
    } catch (e) {
    }

    [
      "name",
      "class",
      "con",
      "atk",
      "def",
      "spd",
      "resist",
      "accuracy",
      "critical_rate",
      "critical_damage"
    ].forEach(function(key) {
      var cell = document.createElement("div")
      cell.classList.add("tcell")
      cell.innerHTML = monster[key]

      row.appendChild(cell)
    })

    table.appendChild(row)
  })

  runes.forEach(function(rune) {
    var table = document.querySelector(".rune-table")
    var row = '<div class="trow"><div class="tcell">' + rune.name + '</div></div>'
    table.insertAdjacentHTML('beforeend', row)
  })
</script>



<!-- Monster Props -->
<!-- <td>Class</td> -->
<!-- <td>Con</td> -->
<!-- <td>Atk</td> -->
<!-- <td>Def</td> -->
<!-- <td>Spd</td> -->
<!-- <td>Resist</td> -->
<!-- <td>Accuracy</td> -->
<!-- <td>Critical Rate</td> -->
<!-- <td>Critical Damage</td> -->

<!-- Rune Props -->
<!-- <th>HP +</th> -->
<!-- <th>HP</th> -->
<!-- <th>ATK +</th> -->
<!-- <th>ATK</th> -->
<!-- <th>DEF +</th> -->
<!-- <th>DEF</th> -->
<!-- <th>SPD +</th> -->
<!-- <th>CRI Rate</th> -->
<!-- <th>CRI Dmg</th> -->
<!-- <th>Resistance</th> -->
<!-- <th>Accuracy</th> -->

app/views/summoners_wars/show.html.erb
<div class="text-center">
  <select class="monster-selector" name="monster-selector" data-monster-details="<%= summoners_war_monsters_path %>">
    <option value=""></option>
    <% @monsters.each do |monster| %>
      <option value="<%= monster.id %>" data-stars="<%= monster.stars %>" data-element="<%= monster.element %>" data-archetype="<%= monster.archetype %>" data-thumb="<%= monster.image_url %>"><%= monster.name %></option>
    <% end %>
  </select>

  <table class="monsters">
    <% [ :HP, :ATK, :DEF, :SPD, :CRI_RATE, :CRI_DMG, :RES, :ACC ].each do |attr_sym| %>
      <% long_sym = Monster.long_code(attr_sym) %>
      <tr type="<%= attr_sym %>" data-long-type="<%= long_sym %>">
        <td class="attr-title"><%= attr_sym.to_s.titleize.upcase %></td>
        <td class="attr-value"></td>
        <td class="rune-value"><input type="text" name="<%= long_sym %>"></td>
        <td class="computed-total"></td>
      </tr>
    <% end %>
  </table>
</div>