config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  get "/blockly" => "index#blockly"
  get "/icons" => "index#icons"
  get "/privacy-policy" => "index#privacy_policy"

  constraints subdomain: "sub" do
    get "/sub" => "index#sub"
  end

  constraints subdomain: "whisper" do
    root "whisper#show", as: :whisper_root
  end

  post "tesla/api/1/vehicles/:vin/command/:command" => "vehicles#command"
  post "tesla/oauth2/v3/token" => "vehicles#token"

  root "index#home"
  post "/talk" => "index#talk"
  get "/nest_subscribe" => "index#nest_subscribe"
  post "/jarvis" => "jarvis#command"
  post "proxy" => "proxy#proxy"
  post "/printer_control" => "printers#control"
  get "map" => "index#map"
  get "playground" => "index#playground"
  resource :ping, only: :create

  resource :whisper, only: [:show], controller: :whisper

  namespace :internal do
    get "auth", to: "auth#check"
  end

  namespace :api do
    namespace :v1 do
      post :alexa, controller: :alexa

      resources :lists, only: [:index, :show, :update, :create, :destroy] do
        post :reorder, on: :collection
        put :order_items, on: :member

        resources :list_items, only: [:index, :show, :update, :create, :destroy] do
          patch :update, on: :collection
          delete :destroy, on: :collection
        end

        resources :sections, only: [:index, :show, :update, :create, :destroy] do
          patch :update, on: :collection
          delete :destroy, on: :collection
        end
        # resources :user_lists, only: [:index, :create, :destroy], path: :users
      end
    end
  end

  resource :jarvis, only: [:show, :update], controller: :quick_actions, as: :user_dashboard do
    get :sync_badge
    get :render_widget
  end

  scope path: :jarvis do
    resources :meal_builders
    resources :list_builders do
      get :manifest, on: :member
      post :toggle_item, on: :member
      patch :update_stock, on: :member
    end
  end

  resources :dashboards, only: [:show, :update], controller: :quick_actions do
    get "/create", on: :collection, action: :get_create
    get :sync_badge
    get :render_widget
  end
  resources :prompts, only: [:index, :show, :update, :destroy], path: :prompts

  scope module: :users do
    get :login,         controller: :sessions,      action: :new
    post :login,        controller: :sessions,      action: :create
    get :logout,        controller: :sessions,      action: :destroy
    delete :logout,     controller: :sessions,      action: :destroy
    get :register,      controller: :registrations, action: :new
    post :register,     controller: :registrations, action: :create
    patch :register,    controller: :registrations, action: :create
    post :guest_signup, controller: :registrations, action: :guest_signup
  end

  resource :money_buckets, path: "/bucket"

  post "webhooks/tesla_telemetry" => "webhooks#tesla_telemetry"
  post "webhooks/tesla_local" => "webhooks#tesla_local"
  post "jil/trigger/:trigger" => "webhooks#jil"
  post "jil/trigger" => "webhooks#jil"
  post "webhooks/jil(/:uuid)" => "webhooks#execute_task"
  get "webhooks/jil(/:uuid)" => "webhooks#execute_task"
  post "webhooks/battery" => "webhooks#battery"
  post "webhooks/report" => "webhooks#report"
  get "webhooks/local_ping" => "webhooks#local_ping"
  post "webhooks/local_ping" => "webhooks#local_ping"
  post "webhooks/jenkins" => "webhooks#jenkins"
  post "webhooks/post" => "webhooks#post"
  post "webhooks/google_pub_sub" => "webhooks#google_pub_sub"
  post "webhooks/email" => "webhooks#email"
  post "webhooks/speak" => "webhooks#speak"
  post "webhooks/notify" => "webhooks#notify"
  get "webhooks/uptime" => "webhooks#uptime"
  post "webhooks/uptime" => "webhooks#uptime"
  post "webhooks/command" => "webhooks#command"
  get "webhooks/auth" => "webhooks#auth"
  get "webhooks/auth/:service" => "webhooks#auth"
  get "webhooks/oauth/:service" => "webhooks#auth"
  post "push_notification_subscribe" => "webhooks#push_notification_subscribe"
  post "push_notification_unsubscribe" => "webhooks#push_notification_unsubscribe"
  post "push_diagnostic" => "webhooks#push_diagnostic"

  get "dashboard" => "dashboard#show"
  resource :dashboard, controller: :dashboard, only: [:show] do
    get :demo, on: :collection
    collection do
      get :octoprint_session
    end
  end

  resource :nfc, only: [:show]

  resources :emails, except: [:destroy, :edit]
  resources :log_trackers, only: [:index, :show]
  post "/ips/ban" => "log_trackers#ban", as: :ban_ip

  resources :surveys
  resources :survey_responses

  resource :calc, only: [:show]

  resources :action_events do
    get :calendar, on: :collection
    get :pullups, on: :collection
    get :feelings, on: :collection
  end

  resource :inventory, controller: :inventory_management do
    resources :boxes do
      collection do
        get :batch
      end
    end
    get :export
    post :import
    post :restore
  end
  get "/b/:id" => "inventory_management#box", as: :box

  resources :scheduled_tasks, path: :schedules

  resource :summoners_war do
    get :runes
    resources :monsters
    resources :monster_skills
  end

  get :account, controller: :users
  resources :api_keys, except: :show
  resources :users, only: [:new, :create, :update]
  resources :lists do
    post :reorder, on: :collection
    member do
      get :manifest
      post :modify_from_message
      post :receive_update
    end
    resources :user_lists, only: [:index, :create, :destroy], path: :users
    resources :list_items
    resources :sections, only: [:edit, :create, :update, :destroy]
  end

  resources :cards, only: [] do
    collection do
      get :deck
    end
  end

  get :random, controller: :random, action: :index
  resources :gcode_splitter, only: [:index]
  resources :colors, only: [:index]
  resources :anonicons, only: [:index, :show], constraints: { id: /[0-9.a-zA-Z]+/ }
  resources :qr_labels, only: [:index, :show]
  get :"svg-editor", controller: :svg_editors, action: :show

  resource :rlcraft, only: [:show, :update]

  resource :little_world, only: [:show] do
    post :save_location
    get :player_login
    get :character_builder
    post :change_clothes
    get :change_clothes, action: :load_character
  end

  namespace :jil do
    get :/, action: :index, controller: :tasks
    get "t/:id" => "tasks#trigger"
    resources :executions, only: [:index, :show] do
      post :replay, on: :member
    end
    post "tasks/reorder", to: "tasks#reorder", as: :reorder_tasks
    resources :tasks do
      post :run, on: :member
      post :duplicate, on: :member
      post :shared_users, on: :member
      post :archive, on: :member
      post :unarchive, on: :member
      resources :executions, only: [:index, :show] do
        post :replay, on: :member
      end
    end
    resources :task_folders, only: [:create, :update, :destroy] do
      post :toggle_collapsed, on: :member
    end
    resources :user_cache, path: :cache
  end
  get "t/:id" => "jil/tasks#trigger"
  # Must be after `jil` namespace so it doesn't overwrite existing routes
  post "jil/:uuid" => "webhooks#execute_task"
  get "jil/:uuid" => "webhooks#execute_task"

  resources :climbs do
    patch :mark, on: :collection
  end

  namespace :bowling, as: nil do
    resources :bowlers, only: [:create] do
      get :throw_stats, on: :collection
    end
    resources :bowling_leagues, path: :leagues do
      get :tms, on: :member
    end
    resources :bowling_sets, path: :series do
      delete "bowler/:bowler_id", on: :member, action: :remove_bowler
    end
    resources :bowling_games, path: "/"
  end

  resources :contacts, except: :show do
    resources :addresses, except: :show
  end
  resources :folders
  resources :pages, except: :index
  get "/pages", to: "folders#index"
  resources :recipes, param: :friendly_id do
    post :export_to_list, on: :member
  end

  resource :maze, only: [:show] do
    collection do
      post ":seed/solve", action: :solve
      match ":seed/solve", action: :preflight, via: :options
      post "/", action: :redirect
      get ".txt", action: "show"
      get ":seed", action: "show"
      get ":seed.txt", action: "show"
    end
  end

  require "sidekiq/web"
  # constraints ->(req) { binding.pry } do
  constraints RoleConstraint.new(:admin) do
    mount ::Sidekiq::Web => "/sidekiq"
    mount ::PgHero::Engine, at: "pghero"
  end
  mount ::ActionCable.server => "/cable"
end

app/controllers/api/v1/list_items_controller.rb
class Api::V1::ListItemsController < Api::V1::BaseController
  skip_before_action :verify_authenticity_token
  before_action :authorize_user_or_guest

  def index
    items = current_list_items
    items = items.with_deleted if params[:with_deleted] == "true"

    serialize items
  end

  def show
    serialize current_item
  end

  def create
    create_params = list_item_params
    if create_params[:category].blank?
      create_params[:name].match(/\A\s*\[(.+)\]\s*([^(\[]+)\s*\z/m) { |m|
        category, name = m[1], m[2]
        next if name.blank?

        section = current_list.sections.where_soft_name(category)
        if section.one?
          create_params[:section_id] = section.first.id
          create_params[:name] = name
        elsif category.present?
          create_params[:category] = category
          create_params[:name] = name
        end
      }
    end
    new_item = current_item(:soft) || current_list_items.new
    new_item.update(create_params.merge(deleted_at: nil, sort_order: nil))

    trigger(:added, new_item)

    serialize new_item
  end

  def update
    current_item.update(list_item_params)
    trigger(:changed, current_item)

    serialize current_item
  end

  def destroy
    current_item.soft_destroy unless current_item.permanent?
    trigger(:removed, current_item)

    serialize current_item
  end

  private

  def trigger(action, item)
    # added | changed | removed
    return if item.blank?

    ::Jil.trigger(current_user, :item, item.jil_serialize(action: action))
  end

  def current_list
    return @current_list if defined?(@current_list)

    @current_list = current_user.lists.find_by(id: params[:list_id])
    @current_list ||= current_user.lists.by_param(params[:list_id]).take!
  end

  def current_list_items
    @current_list_items ||= current_list.list_items.with_deleted
  end

  def current_item(mode=:hard)
    name = list_item_params[:name].presence || params[:name]
    @item = current_list_items.find_by(id: params[:id] || name)
    @item ||= current_list_items.by_formatted_name(name) if name.present?
    @item ||= current_list_items.by_formatted_name(params[:id])
    return @item if mode == :soft

    @current_item ||= current_list_items.find(params[:id] || name)
  end

  def list_item_params
    params.permit(
      :name,
      :checked,
      :category,
      :important,
      :permanent,
    )
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authorize_user_or_guest

  def show
    @list_item = current_list_items.find(params[:id])

    render json: @list_item
  end

  def edit
    @list_item = current_list_items.find(params[:id])
  end

  def create
    current_list = List.find(params[:list_id])
    create_params = list_item_params
    if create_params[:category].blank?
      create_params[:name].match(/\A\s*\[(.+)\]\s*([^(\[]+)\s*\z/m) { |m|
        category, name = m[1], m[2]
        next if name.blank?

        section = current_list.sections.where_soft_name(category)
        if section.one?
          create_params[:section_id] = section.first.id
          create_params[:name] = name
        elsif category.present?
          create_params[:category] = category
          create_params[:name] = name
        end
      }
    end

    new_item = current_item(:soft) || current_list_items.new
    success = new_item.update(create_params.merge(deleted_at: nil, sort_order: nil))

    return render json: { errors: "Cannot create item without a name." } unless success

    trigger(:added, new_item)

    if params[:as_json]
      render json: new_item
    else
      render template: "list_items/show", locals: { item: new_item }, layout: false
    end
  end

  def update
    current_list = List.find(params[:list_id])
    @existing_item = current_list_items.find_by(id: params[:id])
    @existing_item.update(list_item_params)

    trigger(:changed, @existing_item)

    render json: @existing_item
  end

  def destroy
    @list_item = current_list_items.find(params[:id])

    if params[:really_destroy]
      @list_item.destroy
      trigger(:removed, @list_item)
      redirect_to list_path(@list_item.list)
    else
      @list_item.soft_destroy unless @list_item.permanent?
      head :no_content
    end
  end

  private

  def trigger(action, item)
    # added | changed | removed
    return if item.blank?

    ::Jil.trigger(current_user, :item, item.jil_serialize(action: action))
  end

  def current_list
    @list ||= @current_list ||= (
      current_user.lists.find_by(id: params[:list_id]) ||
        current_user.lists.by_param(params[:list_id]).take!
    )
  end

  def current_list_items
    @current_list_items ||= current_list.list_items.with_deleted
  end

  def current_item(mode=:hard)
    name = list_item_params[:name].presence || params[:name]
    @item = current_list_items.find_by(id: params[:id] || name)
    @item ||= current_list_items.by_formatted_name(name) if name.present?
    @item ||= current_list_items.by_formatted_name(params[:id])
    return @item if mode == :soft

    @current_item ||= current_list_items.find(params[:id] || name)
  end

  def list_item_params
    return {} if params[:list_item].blank?

    params.require(:list_item).permit(
      :name,
      :checked,
      :sort_order,
      :important,
      :permanent,
      :category,
      :section_id,
      :schedule,
      schedule: [
        :interval,
        :hour,
        :minute,
        :type,
        :meridian,
        :timezone,
        {
          weekly:  [day: []],
          monthly: [
            :type,
            {
              week: (-1..31).map { |t| { t.to_s => [] } },
              day:  [],
            },
        ],
        },
      ],
    )
  end
end

app/views/list_items/_schedule.html.erb
<%= render_modal("list-item-schedule", "Repeat") do %>
  <%= form_tag list_list_item_path(@list, @list_item), class: "basic text-center", id: "schedule-form", method: :patch, remote: true do |f| %>
    <% options = @list_item.schedule_options %>
    <% base_params = "list_item[schedule]" %>
    <% clean_base = base_params.gsub('[', '_').delete(']') %>

    Reoccur every
    <%= text_field_tag "#{base_params}[interval]", options[:interval], pattern: "[0-9]*", inputmode: "numeric" %>
    <% select_options = [
      ["Minute(s)", :minutely],
      ["Hour(s)",   :hourly],
      ["Day(s)",    :daily],
      ["Week(s)",   :weekly],
      ["Month(s)",  :monthly]
    ] %>
    <%= select_tag "#{base_params}[type]", options_for_select(select_options, selected: options[:type]) %>
    starting at
    <%= text_field_tag "#{base_params}[hour]", options[:hour], id: :hour, pattern: "[0-9]*", inputmode: "numeric" %>:<%= text_field_tag "#{base_params}[minute]", options[:minute], pattern: "[0-9]*", inputmode: "numeric" %>
    <%= check_box_tag "#{base_params}[meridian]", "PM", options[:meridian] == "PM", id: :meridian %>
    <%= label_tag :meridian, "" %>
    <%= hidden_field_tag "#{base_params}[timezone]", options[:timezone], id: :timezone %>

    <div data-watches-selector="#<%= clean_base %>_type" data-watches-value="weekly">
      <div class="calendar">
        <% DateTime::DAYNAMES.each_with_index do |dayname, idx| %>
          <%= check_box_tag "#{base_params}[weekly][day][]", idx, options[:week_days].include?(idx), id: "#{clean_base}_weekly_day_#{idx}" %>
          <%= label_tag "#{clean_base}_weekly_day_#{idx}", dayname.first %>
        <% end %>
      </div>
    </div>

    <div data-watches-selector="#<%= clean_base %>_type" data-watches-value="monthly">
      <div class="radio-wrapper">
        <%= radio_button_tag "#{base_params}[monthly][type]", :daily, options[:days_of_week].none? %>
        <%= label_tag "#{base_params}[monthly][type][daily]" do %>
          <div class="radio-placeholder"></div>
          Days of Month
        <% end %>
      </div>
      <div class="radio-wrapper">
        <%= radio_button_tag "#{base_params}[monthly][type]", :weekly, options[:days_of_week].any? %>
        <%= label_tag "#{base_params}[monthly][type][weekly]" do %>
          <div class="radio-placeholder"></div>
          Days of Week
        <% end %>
      </div>

      <div data-watches-selector="[name='<%= base_params %>[monthly][type]']" data-watches-radio="weekly">
        <div class="calendar">
          <% 5.times do |i| %>
            <% t = i + 1 %>
            <% last_week = t == 5 %>
            <% week_idx = last_week ? -1 : t %>
            <strong><%= last_week ? "Last" : t.ordinalize %></strong>
            <% DateTime::DAYNAMES.each_with_index do |dayname, day_idx| %>
              <%= check_box_tag "#{base_params}[monthly][week][#{day_idx}][]", week_idx, options.dig(:days_of_week, day_idx)&.include?(week_idx), id: "#{clean_base}_monthly_week_#{day_idx}_#{week_idx}" %>
              <%= label_tag "#{clean_base}_monthly_week_#{day_idx}_#{week_idx}", dayname.first %>
            <% end %>
            <br>
          <% end %>
        </div>
      </div>

      <div data-watches-selector="[name='<%= base_params %>[monthly][type]']" data-watches-radio="daily">
        <div class="calendar">
          <% 31.times do |i| %>
            <% t = i + 1 %>
            <%= check_box_tag "#{base_params}[monthly][day][]", t, options[:days_of_month].include?(t), id: "#{clean_base}_monthly_day_#{t}" %>
            <%= label_tag "#{clean_base}_monthly_day_#{t}", t %>
            <% if t % 7 == 0 %><br><% end %>
          <% end %>
          <%= check_box_tag "#{base_params}[monthly][day][]", -1, options[:days_of_month].include?(-1) %>
          <%= label_tag "#{base_params}[monthly][day][]", "Last Day", class: "span-4" %>
        </div>
      </div>
    </div>

    <div class="text-center">
      <%= link_to "Clear", list_list_item_path(@list, @list_item, list_item: {schedule: ""}), data: { method: :patch }, remote: true, class: "btn danger" %>
      <%= submit_tag "Set Schedule" %>
    </div>
  <% end %>
<% end %>

app/views/list_items/edit.html.erb
<%= meta_title "#{@list_item.name}", include_name: false %>
<%= content_for(:favicon) { render "lists/favicon", list: @list } %>
<%= render partial: "schedule" %>

<div class="skinny-container list-container" data-list-id="<%= @list.id %>" data-list-item-id="<%= @list_item.id %>">
  <div class="btn-container">
    <a href="<%= list_path(@list) %>" class="btn">&larr; Back to List</a>
    <%= link_to "Destroy", list_list_item_path(@list, @list_item, really_destroy: true), method: :delete, class: "btn danger pull-right", data: { confirm: "This will remove all trace of this item regardless of schedules set or permanence. This cannot be undone. Are you sure you would like to continue?" } %>
  </div>
  <div class="list-title"><%= @list_item.name %></div>
  <div class="list-error hidden">Disconnected...</div>
  <div class="list-items" data-update-url="<%= list_list_item_path(@list, @list_item) %>">
    <div class="list-item-container" data-editable data-item-url="<%= list_list_item_path(@list, @list_item) %>">
      <div class="list-item-config">
        <div>Category (Click/tap and hold to edit)</div>
      </div>
      <div class="list-item">
        <div class="item-name"><%= @list_item.category %></div>
        <input type="text" name="category" value="<%= @list_item.category %>" class="hidden list-item-field">
      </div>
    </div>
    <% @list_item.options.each_with_index do |(option_key, description), idx| %>
      <div class="list-item-options" data-sort-order="<%= idx %>" data-item-id="<%= @list_item.id %>">
        <%=
          content_tag :input, "", {
            type: "checkbox",
            id: "list_item[#{option_key}]",
            name: "list_item[#{option_key}]",
            class: "list-item-checkbox",
            checked: @list_item.send(option_key),
            data: { "submit-url": list_list_item_path(@list, @list_item) }
          }
        %>
        <label for="list_item[<%= option_key %>]" class="list-item">
          <div class="checkbox-wrapper"></div>
          <div class="item-name">
            <big>&bull; <%= option_key.to_s.titleize %></big>
            <small><%= description %></small>
          </div>
        </label>
      </div>
    <% end %>
    <div class="list-item-options" data-sort-order="<%= @list_item.options.length %>" data-item-id="<%= @list_item.id %>">
      <label for="list_item[schedule]" class="list-item">
        <div class="item-name" data-modal="#list-item-schedule">
          <big>&bull; Schedule</big>
          <p class="portfolio-color schedule"><%= @list_item.schedule_in_words %></p>
          <p class="portfolio-color countdown" data-next-occurrence="<%= (@list_item.schedule_next.to_f * 1000).round %>"></p>
          <small>Click here to configure the schedule. When setting a schedule, after the next date, the item will refresh- adding itself back to your list.</small>
        </div>
      </label>
    </div>
  </div>
</div>

app/views/list_items/index.html.erb
<% list.sectioned_objects.each do |obj| %>
  <% if obj[:type] == :item %>
    <%= render template: "list_items/show", locals: { list: list, item: obj[:object] }, layout: false %>
  <% elsif obj[:type] == :section %>
    <%= render template: "sections/show", locals: { list: list, obj: obj }, layout: false %>
  <% end %>
<% end %>

app/views/list_items/show.html.erb
<% list ||= @list || item.list %>
<% item ||= @list.list_items.new(id: :new) %>
<% template ||= false %>

<div class="list-item-container" data-editable data-sort-order="<%= item.sort_order %>" data-item-id="<%= item.id %>" data-item-url="<%= list_list_item_path(list, item) unless template %>" data-updated="<%= item.updated_at.to_i %>">
  <span class="section-border" style="<%= "border-color: #{section.color};" if defined?(section) && section.present? %>"></span>
  <% unless template %>
    <div class="list-item-config">
      <% if item.important? %>
        <div class="important"><i class="fa fa-star"></i></div>
      <% end %>
      <%= content_tag :div, item.category, class: "category" %>
      <%= content_tag :div, nil,           class: "locked"    if item.permanent? %>
      <%= content_tag :div, nil,           class: "recurring" if item.schedule? %>
    </div>
    <div class="list-item-access">
      <div class="list-item-handle"><i class="fa fa-ellipsis-v"></i></div>
      <a href="<%= edit_list_list_item_path(list, item) %>" class="settings-btn"><i class="fa fa-cog"></i></a>
      <div class="category-btn"><i class="fa fa-tag"></i></div>
    </div>
  <% end %>
  <%= content_tag :input, "",
    type: :checkbox,
    id: "list_item[#{item.id}]",
    class: "list-item-checkbox",
    name: "list_item[#{item.id}]",
    value: "#{item.id}",
    checked: item.deleted?,
    data: {
      "checked-url": "#{list_list_item_path(list, item) unless template}",
      "create-url": "#{list_list_items_path(list) unless template}"
    }
  %>
  <label for="list_item[<%= item.id %>]" class="list-item">
    <div class="checkbox-wrapper"></div>
    <div class="item-name" data-raw="<%= item.name %>"><%= Markdown.new(item.name).to_html %></div>
    <input type="text" name="name" value="<%= item.name %>" class="hidden list-item-field">
    <input type="text" name="category" value="<%= item.category %>" placeholder="Category" class="hidden list-item-category-field">
  </label>
</div>